# Generated by Django 4.1.3 on 2023-01-15 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('pic', models.ImageField(upload_to='')),
                ('github', models.URLField()),
                ('link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
