# Generated by Django 4.1.3 on 2023-01-15 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_project_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='subname',
            field=models.CharField(default='project-sub', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(default='project', max_length=100),
        ),
    ]
